//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogisticsProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Naczepy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Naczepy()
        {
            this.Pojazdy = new HashSet<Pojazdy>();
        }
    
        public int ID { get; set; }
        public string NrRejestracyjny { get; set; }
        public int Ladownosc { get; set; }
        public double Dlugosc { get; set; }
        public double Szerokosc { get; set; }
        public double Wysokosc { get; set; }
        public bool Chlodnia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pojazdy> Pojazdy { get; set; }
    }
}
