//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogisticsProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoweZamowienia
    {
        public int Id { get; set; }
        public string NazwaFirmy { get; set; }
        public string AdresKontaktowy { get; set; }
        public string Wlasciciel { get; set; }
        public string Email { get; set; }
        public int MasaLadunku { get; set; }
        public double DlugoscLadunku { get; set; }
        public double SzerokoscLadunku { get; set; }
        public double WysokoscLadunku { get; set; }
        public bool WymaganaChlodnia { get; set; }
        public System.DateTime DataZaladunku { get; set; }
        public System.DateTime DataRozladunku { get; set; }
        public string MiejsceZaladunku { get; set; }
        public string MiejsceRozladunku { get; set; }
    }
}
