//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogisticsProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Przewoznicy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Przewoznicy()
        {
            this.Pojazdy = new HashSet<Pojazdy>();
        }
    
        public int ID { get; set; }
        public string Nazwa { get; set; }
        public string AdresKontaktowy { get; set; }
        public string Wlasciciel { get; set; }
        public string NrKomorkowy { get; set; }
        public string NrKonta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pojazdy> Pojazdy { get; set; }
    }
}
