//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogisticsProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trasy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trasy()
        {
            this.Zlecenia = new HashSet<Zlecenia>();
        }
    
        public int ID { get; set; }
        public int Dlugosc { get; set; }
        public double OplatyDodatkowe { get; set; }
        public int IDCentrum1 { get; set; }
        public int IDCentrum2 { get; set; }
    
        public virtual CentraLogistyczne CentraLogistyczne { get; set; }
        public virtual CentraLogistyczne CentraLogistyczne1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zlecenia> Zlecenia { get; set; }
    }
}
