//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogisticsProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zlecenia
    {
        public int ID { get; set; }
        public System.DateTime DataZaladunku { get; set; }
        public System.DateTime DataRozladunku { get; set; }
        public Nullable<int> IDLadunku { get; set; }
        public Nullable<int> IDPojazdu { get; set; }
        public Nullable<int> IDTrasy { get; set; }
    
        public virtual Ladunki Ladunki { get; set; }
        public virtual Pojazdy Pojazdy { get; set; }
        public virtual Trasy Trasy { get; set; }
    }
}
